---
title: "Blog"
output: 
  html_document:
    toc: no
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message=FALSE,warning=FALSE)
library(DT)
```

##This Blog 
This my contribution to the fields of data science, business analytics, information technology, and variations on those themes.

```{r blog_df, echo=TRUE}

# instead I should read all .rmd files in main dir
  # and exclude non-blog posts!
  # because blog posts will quickly outweigh non-blog posts
blog_df <- data.frame(
  filename = c("create_interesting_datasets"
               ,"ifelse_NA_trap"
               ,"building_this_site"
               ,"ed_api")
)

# pull some text from each file for a sample
blog_df$intros <- sapply(
  paste0(blog_df$filename,".Rmd"),function(x){
    paste0(substr(gsub(".*##",
     "",
     paste(readLines(x)[1:50],collapse = " "),
     perl = TRUE
    ),
    1,70)," ...")
    }
  )

blog_df$created_at <- as.Date(file.info(paste0(blog_df$filename,".html"))$ctime)
blog_df$updated_at <- as.Date(file.info(paste0(blog_df$filename,".html"))$mtime)
blog_df$size <- file.info(paste0(blog_df$filename,".Rmd"))$size
blog_df$lines <- sapply(
  paste0(blog_df$filename,".Rmd"),function(x) blog_df$filename = length(readLines(x)))


blog_df$titles <- sapply(
  paste0(blog_df$filename,".Rmd"),function(x){
    gsub('"',
         "",
         gsub("title: ",
           "",
           readLines(x)[2]
          )
    )
    }
  )

#wrap filename in raw html
#give it the actual post title
blog_df$filename <- paste0("<a href='",blog_df$filename,".html' target='_blank'>",blog_df$titles,"</a>")

# no longer need plain text titles
blog_df$titles <- NULL

blog_df <- dplyr::arrange(blog_df,dplyr::desc(created_at))

# define formate for header
col_format <- JS(
  "function(settings, json) {",
  "$(this.api().table().header()).css({'background-color': '#252525', 'color': '#FFFFFF'});",
  "}")

datatable(blog_df
          ,escape = FALSE
          ,rownames=FALSE
          ,colnames = c('Title',
                        'Content Snippet',
                       'Created At',
                       'Updated At',
                       'Post Size (bytes)',
                       'Post Length (lines)')
          ,options=list(
            initComplete = col_format,
            pageLength=25,
            columnDefs = list(list(className = 'dt-center',targets=3:ncol(blog_df)-1)), #center all but first column
            dom = 'frtpB'
          )) %>%
      formatStyle(
        'size',
        background = styleColorBar(range(0,max(blog_df$size)), 'orange'),
        backgroundSize = '98% 75%',
        backgroundRepeat = 'no-repeat',
        backgroundPosition = 'left') %>%
        formatStyle(
        'lines',
        background = styleColorBar(range(0,max(blog_df$lines)), 'orange'),
        backgroundSize = '98% 75%',
        backgroundRepeat = 'no-repeat',
        backgroundPosition = 'left') %>%
      formatStyle(columns = "filename", 
              # backgroundColor = 'gray',
              color = 'black',
              fontWeight = 'bold')

```



