---
title: "U.S. Colleges"
author: "Noah Pollock"
output:
  html_document:
    toc: no
    code_folding: hide
---

```{r setup, include=FALSE}
library(highcharter)
library(dplyr)
library(leaflet)
library(viridisLite)
library(treemap)
library(flexdashboard)

knitr::opts_chunk$set(echo = TRUE,message=FALSE,warning=FALSE)

ed_df <- read.csv("ed_api.csv",
                  stringsAsFactors = FALSE) %>% 
  rename_all(substring,first=9) # remove dev-category prefix

thm <- 
  hc_theme(
    colors = c("#1a6ecc", "#434348", "#90ed7d"),
    chart = list(
      backgroundColor = "transparent",
      style = list(fontFamily = "Source Sans Pro")
    ),
    xAxis = list(
      gridLineWidth = 1
    )
  )

# would like to directly call api
  # though not feasible with mapping...
# use method to ask for API key
# is it still embedded somewhere in code?

```

## Enrollment: {.tabset data-width=400}

### Latitude
```{r lat}

pdata <- ed_df %>%
  mutate(lat_round = round(location.lat,0)) %>%
  select(lat_round,latest.student.enrollment.all) %>%
  filter(!is.na(latest.student.enrollment.all)) %>%
  group_by(lat_round) %>%
  summarise(students = sum(latest.student.enrollment.all)) %>%
  arrange(lat_round)

pdata %>% 
  hchart("line",hcaes(x="lat_round",y="students")) %>% 
  hc_add_theme(thm)
```

### Longitude
```{r lon}

pdata <- ed_df %>%
  mutate(lon_round = round(location.lon,0)) %>%
  select(lon_round,latest.student.enrollment.all) %>%
  filter(!is.na(latest.student.enrollment.all)) %>%
  group_by(lon_round) %>%
  summarise(students = sum(latest.student.enrollment.all)) %>%
  arrange(lon_round)

pdata %>% 
  hchart("line",hcaes(x="lon_round",y="students")) %>% 
  hc_add_theme(thm)
```

### Mapped (Lat and Lon)

```{r map}

pal <- colorNumeric(
  palette = c("orange","red"),
  domain = ed_df$latest.student.enrollment.all)

# discretify continuous variables
# qpal <- colorQuantile("Blues", countries$gdp_md_est, n = 7)

leaflet() %>% addTiles() %>%
  addCircleMarkers(data = ed_df,
                   lat = ~location.lat, lng = ~location.lon,
                   color = ~pal(latest.student.enrollment.all),
                    weight = 1,
                   fillOpacity = .6,
                   radius = ~(latest.student.enrollment.all / 1500),
                   stroke = FALSE,
                   popup = ~paste0("<strong>",school.name,"</strong><br>",
                                   "Enrollment: ",latest.student.enrollment.all),
                    labelOptions = labelOptions(
    style = list("font-weight" = "normal", padding = "3px 8px"),
    textsize = "15px",
    direction = "auto"))

```



```{r treemap}
## Earnings by Institution Type

#, fig.keep='none'
# tdata <- ed_df %>%
#   group_by(school.online_only
#            ,school.under_investigation) %>%
#   summarise(Median = median(latest.earnings.10_yrs_after_entry.median,na.rm=TRUE)) %>%
#   filter(!is.na(Median)) %>%
#   mutate(online_only = ifelse(school.online_only==0,"No","Yes"),
#          under_HCM_investigation = ifelse(school.under_investigation==1,"Yes","No")) %>%
#   ungroup() %>%
#   select(online_only
#          ,under_HCM_investigation
#          ,Median)
#   
# tm <- treemap(tdata, index = c("online_only", "under_HCM_investigation"),
#               vSize = "Median", vColor = "Median",
#               type = "value", palette = rev(viridis(6)))
# 
# highchart() %>% 
#   hc_add_series_treemap(tm, allowDrillToNode = TRUE,
#                         layoutAlgorithm = "squarified") %>% 
#   hc_add_theme(thm)

# Heightened Cash Monitoring 2
# 
# data("Groceries", package = "arules")
# dfitems <- tbl_df(Groceries@itemInfo)
# 
# set.seed(10)
# 
# dfitemsg <- dfitems %>%
#   mutate(category = gsub(" ", "-", level1),
#          subcategory = gsub(" ", "-", level2)) %>%
#   group_by(category, subcategory) %>%
#   summarise(sales = n() ^ 3 ) %>%
#   ungroup() %>%
#   sample_n(31)
# 
# tm <- treemap(dfitemsg, index = c("category", "subcategory"),
#               vSize = "sales", vColor = "sales",
#               type = "value", palette = rev(viridis(6)))
# 
# highchart() %>% 
#   hc_add_series_treemap(tm, allowDrillToNode = TRUE,
#                         layoutAlgorithm = "squarified") %>% 
#   hc_add_theme(thm)
```

## Top 10 Earners

```{r top_10_earners}


ed_df %>%
  group_by(school.name) %>%
  summarise(Median = median(latest.earnings.10_yrs_after_entry.median,na.rm=TRUE)) %>%
  arrange(desc(Median)) %>%
  slice(1:10) %>%
  # hchart(showInLegend = FALSE, name = "school.name", pointWidth = 10) %>%
  hchart("bar",hcaes(x="school.name",y="Median")) %>%
  hc_add_theme(thm)

# set.seed(2)
# 
# nprods <- 10
# 
# dfitems %>% 
#   sample_n(nprods) %>% 
#   .$labels %>% 
#   rep(times = sort(sample( 1e4:2e4, size = nprods), decreasing = TRUE)) %>% 
#   factor(levels = unique(.)) %>% 
#   hchart(showInLegend = FALSE, name = "Sales", pointWidth = 10) %>% 
#   hc_add_theme(thm) %>% 
#   hc_chart(type = "bar")
  
  
```