---
title: "README"
author: "Noah Pollock"
date: "December 12, 2018"
output: md_document
---

## Scope
I built a website and included some interesting content throughout including several posts and a shiny dashboard that mimics popular Business Intelligence tools.

## Files Uploaded
I have uploaded this README and most of the R Markdown files I wrote to generate the site. One R Markdown file was excluded because it contains an API Key to the U.S. Department of Education API. Hopefully you won't find it on github either (ha!).

## Steps to Test
The website is published on the internet at GitHub. Click the link below to test it.

* [Website Link](https://ncpollock.github.io/)
* [Screencast is included in a PPT presentation within the folder I uploaded or at this link](https://1drv.ms/p/s!AnbrF2Up8Q7Ag8w4bHkJS2mWR4b04Q)
* [Post on how I created the site](https://ncpollock.github.io/building_this_site.html)

Because my site is live on the web and per our conversation, I didn't spend time making the files included here executable. Still, you may be able to run a local version by simply initiating an R Project in the directory and then reopening RStudio. Also, the full code is available in my [GitHub Repo](https://github.com/ncpollock/)

I leveraged the following tools and technologies:

* R, RStudio, and shinyapps.io
* Git and GitHub, and GitHub Pages
* Python
* HTML and CSS


